name: Test

on:
  push:
    branches:
      - master
      - '*'
  pull_request:
    branches: [master]

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: [stable, beta]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: UziTech/action-setup-atom@v1
      with:
        channel: ${{ matrix.channel }}
    - name: Atom version
      run: atom -v
    - name: APM version
      run: apm -v
    - name: Install dependencies
      run: apm ci
    - name: Install test packages
      run: apm install aligner-javascript aligner-coffeescript aligner-scss
    - name: Run tests 🧪
      run: atom --test spec
